# Generated by Django 2.0 on 2021-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=300)),
                ('poster', models.TextField(max_length=5000)),
            ],
        ),
    ]
