# Generated by Django 2.0 on 2021-04-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movietest'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietest',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Product Image'),
        ),
    ]
