# Generated by Django 2.0 on 2021-04-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210414_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=300)),
                ('poster', models.URLField(default=None, null=True)),
                ('rating', models.FloatField(default=0)),
                ('director', models.CharField(max_length=300)),
                ('cast', models.CharField(max_length=800)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='MovieTest',
        ),
    ]
