# Generated by Django 2.0 on 2021-04-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210414_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieclass',
            name='cast',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='movieclass',
            name='director',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movieclass',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movieclass',
            name='year',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
