# Generated by Django 2.0 on 2021-04-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210414_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
