# Generated by Django 2.0 on 2021-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_movieclass_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieclass',
            name='year',
            field=models.IntegerField(max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='movieclass',
            unique_together={('title', 'year')},
        ),
    ]
