# Generated by Django 2.0 on 2021-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210415_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieclass',
            name='year',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='movieclass',
            unique_together=set(),
        ),
    ]
