# Generated by Django 2.0 on 2021-04-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_movieclass_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='MovieClass',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
