# Generated by Django 3.2 on 2021-04-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_movieclass_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieclass',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
