# Generated by Django 3.2 on 2021-04-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_movieclass_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieclass',
            name='movie_id',
        ),
        migrations.AlterField(
            model_name='movieclass',
            name='description',
            field=models.TextField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='movieclass',
            name='director',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='movieclass',
            name='title',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='movieclass',
            name='year',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
